### ISSUE TITLE
OSVR and Oculus 1.4.0

### ISSUE THREAD

**Issue by MisterKrabs** [OSVR/OSVR-Oculus-Rift#16]
I am glad I found OSVR, as I want to use the Oculus Rift on a motion simulator platform (description [here](http://gamedev.stackexchange.com/questions/120865/oculus-rift-on-motion-simulator-platform)).
I am currently using the Oculus SDK 1.4.0 together with the Oculus DK2 and need to switch to OSVR, as it seems. However, I can't get OSVR to work with the Oculus, as the server does not recognize the HMD.
I used the precompiled binaries to get started (runtime 1194, 64 bits; Oculus Rift build 43, 1.4.0 (tried both 32 and 64 bit, as suggested in another Issue)), but I only get [this](http://pastebin.com/n3M4yF9f) output.
Do you have any suggestions?

**Comment by MisterKrabs** [comment]
Okay, one problem solved, one new to go.
It detects the oculus if I have the oculus service running (for some reason I thought it needed to be disabled).
The oculus tracking camera is however still not recognized (see [here](http://pastebin.com/MCAVtVtG)).
What's the reason?

**Comment by nmanjofo** [comment]
How did you manage to make it recognized? What runtime do you use with DK2? And what platform (Win/Tux)? I have issues recognizing the DK2 as well on Windows.

Thanks

**Comment by MisterKrabs** [comment]
As the title says, I use the Oculus SDK 1.4.0.
This is on a Windows 7 x64 platform.
Just yesterday I managed to get it working: Instead of changing simply the _display_ line in the server config to Oculus DK2 you really just have to overwrite all the content of the default configuration with the Oculus DK2 sample config. Thus the proper server config file just has the single entry 

```
{
    "display": "displays/Oculus_DK2.json"
}
```

note that the name and path may be different in your case, but this is the whole content of my config.
This does not solve my original problem however, since this relies on the data processed by the oculus runtime and originally I wanted to alter the sensor fusion, which is why I experimented with OSVR.

**Comment by nmanjofo** [comment]
Yes, U have SDK ver 1.4.0, but what runtime do you use (= DK2 drivers)? I have SDK ver 1.3.2 and runtime 0.8.0.0. Will try that 1.4.0. SDK...

I use the config file that is a part of the plugin (osvr_server_config.oculusrift.sample.json), which I pass as argument to osvr_server.

The thing is that the rift plugin fails to initialize in my case, e.g. ovr_Initialize returns -3001 (Couldn't load LibOVRRT) as far as I am able to debug it.

**Comment by MisterKrabs** [comment]
I am not at the workshop right now, but I simply use the newest runtime available as of now.

**Comment by nmanjofo** [comment]
SOLVED - I installed runtime 1.4.0 as well as SDK 1.4.0 and DK2 is now detected. Tracker Viewer now shows proper tracking, but no rendering examples seem to work...

**Comment by godbyk** [comment]
@nmanjofo You should keep the runtime and SDK version numbers synchronized. Oculus isn't very good about providing backward- and forward-compatibility between those two components.

**Comment by nmanjofo** [comment]
I see now... thank You for help... but now, apart from Tracker Viewer, I still cannot run any rendering demos. Do You please know, how to set up rendering parameters in server configuration for DK2?

**Comment by lishuwei115** [comment]
@nmanjofo hello Is your problem solved?，i also use DK2 and it can not rendering anying.only can track position and rotation,please tell me how you slove finally,thank you very much
