### ISSUE TITLE
Precompiled release?

### ISSUE THREAD

**Issue by Bungpiece** [OSVR/OSVR-Oculus-Rift#18]
I hate to be that guy. But I would greatly appreciate  it. I'm new to osvr and I'm just not having any luck myself. Or any pointers to where I've gone wrong would be great. Never used cmake before.
(Forgot to mention this is for the new 1.6 run time release.)

"CMake Error at C:/OSVR-Core-0.6/cmake-local/CMakeBoostHelper.cmake:11 (include):
  include could not find load file:

```
GetMSVCVersion
```

Call Stack (most recent call first):
  C:/OSVR-Core-0.6/cmake-local/CMakeBoostHelper.cmake:15 (_boosthelper_includehelper)
  C:/OSVR-Core-0.6/cmake-local/osvrConfigBuildTreePaths.cmake:21 (include)
  C:/OSVR-Core-0.6/cmake-local/osvrConfig.cmake:3 (include)
  CMakeLists.txt:11 (find_package)

CMake Error at C:/OSVR-Core-0.6/cmake-local/CMakeBoostHelper.cmake:16 (get_msvc_major_minor_version):
  Unknown CMake command "get_msvc_major_minor_version".
Call Stack (most recent call first):
  C:/OSVR-Core-0.6/cmake-local/osvrConfigBuildTreePaths.cmake:21 (include)
  C:/OSVR-Core-0.6/cmake-local/osvrConfig.cmake:3 (include)
  CMakeLists.txt:11 (find_package)"

**Comment by godbyk** [comment]
Just a few minutes ago, we built the plugin for version 1.6.0 of the Oculus SDK in case that's useful. You may download it from [here](http://access.osvr.com/binary/oculus).

The error messages that you've shown here indicate a problem building OSVR-Core, so it'd be better to file this issue [over there](https://github.com/OSVR/OSVR-Core) instead.

**Comment by Bungpiece** [comment]
Thanks for your help. Sorry for the clutter.
