### ISSUE TITLE
License compliance - health and safety notice

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Oculus-Rift#2]
Seen recently in another Oculus application: https://github.com/bjornblissing/osgoculusviewer/issues/35

**Comment by godbyk** [comment]
Starting with Oculus SDK 0.6.x:

> Removed the health-and-safety-warning related functions (e.g. `ovrHmd_GetHSWDisplayState`). The HSW functionality is now handled automatically.
