### ISSUE TITLE
Bad pixel smear with OMLED display

### ISSUE THREAD

**Issue by booty156** [OSVR/OSVR-Oculus-Rift#23]
How can I solve this? I've correctly added my display to OSVR. But when I moved about the colors smear and it's really bad

**Comment by godbyk** [comment]
This repository is for the OSVR plugin that allows OSVR to work with the Oculus Rift HMDs.

I would recommend contacting [OSVR support](http://www.razersupport.com/hdk2) for assistance with your OSVR HDK.
