### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Oculus-Rift#8]
Specifically, that it requires a build of https://github.com/vrpn/vrpn/tree/feature/oculus-rift and what versions of the Oculus SDK it supports.

**Comment by JeffBail** [comment]
Is OVR SDK 0.8 supported?

It would also be good to label the OVR SDK required for the binaries which are available on http://access.osvr.com/binary/oculus

**Comment by peroht** [comment]
@JeffBail No, seems not to . I tried it using the 784 just now but the osvr_server just stalls on "instantiating plugins".

**Comment by rpavlik** [comment]
No, the master branch is building with 0.4 on CI (so presumably works  with 0.5?) and there's a much simpler but incomplete implementation in a branch that is based on 0.6, iirc.

**Comment by godbyk** [comment]
I'll be working on upgrading this to work with the newer OVR SDKs either this week or next.

The older version of the SDK to that the master branch works with compiles against a static OVR library. I'm guessing this older library doesn't communicate properly with the newer Oculus runtimes.

**Comment by godbyk** [comment]
VRPN is no longer required for this plugin. This is fixed by PR #10.
